sonar:sonar and clean verfy sonar:sonar
ERROR: Failed to execute goal on project apache-mahout-distribution: Could not resolve dependencies for project org.apache.mahout:apache-mahout-distribution:pom:0.12.3: The following artifacts could not be resolved: org.apache.mahout:mahout-math:jar:0.12.3, org.apache.mahout:mahout-integration:jar:0.12.3, org.apache.mahout:mahout-hdfs:jar:0.12.3, org.apache.mahout:mahout-mr:jar:0.12.3, org.apache.mahout:mahout-examples:jar:0.12.3, org.apache.mahout:mahout-h2o_2.10:jar:0.12.3, org.apache.mahout:mahout-spark_2.10:jar:0.12.3, org.apache.mahout:mahout-flink_2.10:jar:0.12.3, org.apache.mahout:mahout-spark-shell_2.10:jar:0.12.3, org.apache.mahout:mahout-math-scala_2.10:jar:0.12.3: Failure to find org.apache.mahout:mahout-math:jar:0.12.3 in https://repository.cloudera.com/artifactory/cloudera-repos/ was cached in the local repository, resolution will not be reattempted until the update interval of cloudera has elapsed or updates are forced
Solution: DependencyResolutionException

[WARNING] The POM for org.eclipse.m2e:lifecycle-mapping:jar:1.0.0 is missing, no dependency information available
[WARNING] Failed to retrieve plugin descriptor for org.eclipse.m2e:lifecycle-mapping:1.0.0: Plugin org.eclipse.m2e:lifecycle-mapping:1.0.0 or one of its dependencies could not be resolved: Failure to find org.eclipse.m2e:lifecycle-mapping:jar:1.0.0 in https://repo.maven.apache.org/maven2 was cached in the local repository, resolution will not be reattempted until the update interval of central has elapsed or updates are forced
SOLUTION: MojoExecutionException
p.s. http://localhost:9000 viene visualizzato con l'avvio di sonarqube ma non vengono visualizzati i progetti analizzati, quindi l'analisi è stata fatta guardando la console da eclipse